version: "2"

services:
  consul:
    container_name: consul
    image: consul
    command: agent -join 192.168.50.4 -domain vagrant.dev --advertise 192.168.50.5 -node=node2 -datacenter cluster --client=0.0.0.0 -recursor 8.8.8.8 -ui
    restart: always
    network_mode: host
    volumes:
      - consul-data:/consul/data

  sentinel:
    container_name: sentinel
    image: sentinel:dev
    restart: always
    network_mode: host
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
    - consul

volumes:
  consul-data:
    driver: local
